### PR TITLE
added underscore as valid symbol for domain

### PR DESCRIPTION
**Pull request by mastak**
Thank you for making this!

There are sites with the underscore in the name, so I think it should be correct pattern
Examples: 
http://jurnalsda_pusair.pu.go.id 
http://contributii_botanice.reviste.ubbcluj.ro 
http://nova_scientia.delasalle.edu.mx

### CODE REVIEW

**Comment by insightindustry** [comment]
Thanks! This is a great catch, and you are absolutely correct that underscores fully compliant with RFC 2181 for domain names. I appreciate the fix, and I'll be reviewing it for inclusion in the next release.

**Comment by mastak** [comment]
Cool!

When can I expect a release with this fix?

**Comment by insightindustry** [comment]
I'm hoping to get the new version released before Monday - there's still one bug showing up in Python 2.7 for a different bug fix related to domains and URLs in #26 which I need to resolve.

**Comment by insightindustry** [comment]
@mastak : Just an FYI in case you're not subscribed to notifications, **v.1.3.2** with the underscore fix included has just been released.

**Comment by mastak** [comment]
Excellent, thank a lot!

**Pull request merged**
